camel:
  scheduler:
    delay: 6000
    name: BTCUSDT_RATE
  from:
    scheduler: "scheduler://${camel.scheduler.name}?delay=${camel.scheduler.delay}"
services:
  rate:
    url: https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT
springdoc:
  api-docs:
    path: /docs
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mymealy?autoReconnect=true&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8888